[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "postgresql",
    "libpq",
    "zlib",
    "libjpeg",
    "libtiff",
    "libffi",
    "libmagic"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src:/opt/render/project/src/wildlife_management gunicorn --chdir /opt/render/project/src wildlife_management.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --access-logfile - --error-logfile - --log-level info" 