services:
  - type: web
    name: wildlife-management
    env: python
    region: oregon
    buildCommand: |
      python -c 'import sys; assert sys.version_info[:2] == (3,11), "Python 3.11.x required"' && \
      chmod +x build.sh && ./build.sh
    startCommand: gunicorn wildlife_management.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --access-logfile - --error-logfile - --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: wildlife_management.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: PROJECT_ROOT
        value: /opt/render/project/src
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/wildlife_management
    healthCheckPath: /health/
    autoDeploy: false  # Disable auto-deploy to ensure clean builds
    buildFilter:
      paths:
        - wildlife_management/**
        - core/**
        - templates/**
        - static/**
        - requirements.txt
        - build.sh
        - render.yaml 