services:
  - type: web
    name: wildlife-management
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: wildlife_management.settings
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health/ 