# Generated by Django 5.1.6 on 2025-02-17 00:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be between -90 and 90 degrees'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be between -90 and 90 degrees')])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be between -180 and 180 degrees'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be between -180 and 180 degrees')])),
                ('orientation', models.FloatField(blank=True, help_text='Camera orientation in degrees (0-360°, where 0° is North)', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Orientation must be between 0 and 360 degrees'), django.core.validators.MaxValueValidator(360.0, message='Orientation must be between 0 and 360 degrees')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Supported formats: JPG, PNG, GIF', upload_to='media/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.camera')),
                ('tags', models.ManyToManyField(blank=True, related_name='media_files', to='core.tag')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
