# Generated by Django 5.1.6 on 2025-02-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_tag_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='camera_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='camera_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='capture_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the photo was taken (from EXIF data)', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='exposure_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='f_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='focal_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='has_exif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='iso_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
